import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
await mkdir('test-results/camera-turf',{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),results=[],errors=[];
const check=(name,pass,detail)=>{assert.ok(pass,`${name}: ${JSON.stringify(detail)}`);results.push({name,detail});console.log(`PASS ${name}`)};
try{
 const p=await browser.newPage({viewport:{width:1440,height:900}});p.on('pageerror',e=>errors.push(e.message));p.on('console',e=>{if(e.type()==='error')errors.push(e.text())});
 await p.goto(process.env.GAME_URL||'http://127.0.0.1:5179');await p.waitForFunction(()=>window.__game?.view&&!document.querySelector('#loading'));
 await p.evaluate(()=>{window.requestAnimationFrame=()=>0;window.__game.testing=true;});await p.waitForTimeout(100);
 const passThrough=await p.evaluate(async()=>{const g=window.__game,T=await import('/node_modules/.vite/deps/three.js'),{FIELD}=await import('/src/config.ts'),{FollowCamera}=await import('/src/follow-camera.ts');g.scenario('drive');const rows=[];
  for(const side of [-1,1])for(const angle of [.25,.6,.9,1.2]){
   const normal=new T.Vector3(-side*Math.sin(angle),Math.cos(angle),0),point=new T.Vector3(side*(FIELD.width-FIELD.rampRadius+FIELD.rampRadius*Math.sin(angle)),FIELD.rampRadius*(1-Math.cos(angle)),12).addScaledVector(normal,.335),ball=new T.Vector3(0,3,0),rig=new FollowCamera(),camera=new T.PerspectiveCamera(69,1.6,.15,550),free=new FollowCamera(),expected=new T.PerspectiveCamera(69,1.6,.15,550);
   rig.update(camera,point,new T.Quaternion(),ball,14,true,false,0,true,(a,b)=>g.physics.cameraClearance(a,b));free.update(expected,point,new T.Quaternion(),ball,14,true,false,0,true,(a,b)=>a.distanceTo(b));
   rows.push({side,angle,match:camera.position.distanceTo(expected.position),distance:camera.position.distanceTo(point),outside:Math.abs(camera.position.x)>FIELD.width});
  }return rows;});
 check('Ramp approaches retain the intended camera orbit and distance',passThrough.every(r=>r.match<.001&&r.distance>4)&&passThrough.some(r=>r.outside),passThrough);
 const ride=await p.evaluate(()=>{const g=window.__game,v=g.view;g.scenario('wall-drive');v.ballCam=true;v.cameraReady=false;v.update(0,'playing');let maxStep=0,outside=0,hidden=0;const trace=[];for(let i=0;i<120;i++){const before=v.camera.position.clone();g.advance(1/60,{throttle:1,boost:true});const car=v.player.root.position.clone().project(v.camera),ball=v.ball.position.clone().project(v.camera);maxStep=Math.max(maxStep,before.distanceTo(v.camera.position));if(Math.abs(v.camera.position.x)>40.96)outside++;if(Math.abs(car.x)>1||Math.abs(car.y)>1||car.z>1||Math.abs(ball.x)>1||Math.abs(ball.y)>1||ball.z>1)hidden++;if(i%20===0)trace.push({car:v.player.root.position.toArray(),camera:v.camera.position.toArray()});}return{maxStep,outside,hidden,trace};});
 check('Driving up a wall passes the camera outside without a framing snap',ride.outside>15&&ride.hidden===0&&ride.maxStep<.75,ride);
 for(const quality of ['performance','high','ultra']){
  const sides=await p.evaluate(async quality=>{const g=window.__game,v=g.view,T=await import('/node_modules/.vite/deps/three.js'),{FIELD}=await import('/src/config.ts');g.scenario('drive');v.setQuality(quality);v.ballCam=true;const angle=.9,normal=new T.Vector3(-Math.sin(angle),Math.cos(angle),0),point=new T.Vector3(FIELD.width-FIELD.rampRadius+FIELD.rampRadius*Math.sin(angle),FIELD.rampRadius*(1-Math.cos(angle)),12).addScaledVector(normal,.335);g.physics.player.body.setTranslation(point,true);g.physics.player.body.setRotation(new T.Quaternion().setFromUnitVectors(new T.Vector3(0,1,0),normal),true);g.physics.ball.setTranslation({x:0,y:3,z:0},true);v.cameraReady=false;v.update(0,'playing');g.hud.camera(true);g.hud.bindings(g.controls);g.positionLabels();v.draw();const ramp=v.scene.getObjectByName('arena-ramp'),back=v.scene.getObjectByName('arena-ramp-transparent-back');return{front:ramp.material.side,back:back.material.side,transparent:back.material.transparent,depthWrite:back.material.depthWrite,drawCalls:v.renderer.info.render.calls};},quality);
  check(`${quality}: ramps have opaque inner tiles and transparent outer grids`,sides.front===0&&sides.back===1&&sides.transparent&&!sides.depthWrite,sides);
  await p.screenshot({path:`test-results/camera-turf/${quality}-outside.png`});
 }
 const dirt=await p.evaluate(()=>{const g=window.__game,v=g.view,fx=v.turfDebris[0],rows=[];
  for(const [name,input]of [['straight',{}],['turn',{steer:.8}],['drift',{steer:.8,drift:true}]]){g.scenario('drive');g.physics.resetCar(g.physics.player,10,20);g.advance(.25);g.physics.player.body.setLinvel({x:0,y:0,z:-15},true);fx.reset();const before=fx.cursor;let max=0;for(let i=0;i<60;i++){g.advance(1/60,{throttle:1,...input});max=Math.max(max,fx.mesh.count);}rows.push({name,emitted:fx.cursor-before,max,count:fx.mesh.count});}
  const before=Array.from(fx.mesh.instanceMatrix.array);v.update(0,'playing');const frozen=before.every((n,i)=>n===fx.mesh.instanceMatrix.array[i]);g.physics.player.grounded=false;for(let i=0;i<90;i++)v.update(1/60,'playing');const expired=fx.mesh.count;
  const excluded=[];for(const [name,x,y,z,grounded]of [['air',10,8,10,false],['goal',0,.335,55,true],['pad',-31,.335,0,true],['ramp',40,1,10,true]]){g.physics.player.body.setTranslation({x,y,z},true);g.physics.player.grounded=grounded;fx.reset();const start=fx.cursor;for(let i=0;i<60;i++)v.update(1/60,'playing');excluded.push({name,count:fx.cursor-start});}
  return{rows,frozen,expired,excluded};});
 check('Tire contacts kick up occasional clumps and more during turns and drift',dirt.rows[0].emitted>0&&dirt.rows[1].emitted>dirt.rows[0].emitted*2&&dirt.rows[2].emitted>dirt.rows[1].emitted&&dirt.rows.every(r=>r.max<=192),dirt.rows);
 check('Debris freezes on pause, expires, and never spawns on air, goals, pads or ramps',dirt.frozen&&dirt.expired===0&&dirt.excluded.every(r=>r.count===0),dirt);
 await p.evaluate(()=>{const g=window.__game;g.scenario('drive');g.physics.resetCar(g.physics.player,10,20);g.advance(.25);g.physics.player.body.setLinvel({x:0,y:0,z:-15},true);g.view.turfDebris[0].reset();for(let i=0;i<60;i++)g.advance(1/60,{throttle:1,steer:.8,drift:true});const v=g.view,c=v.player.root.position;v.camera.position.set(c.x-2.8,1.2,c.z+2.8);v.camera.lookAt(c.x,.25,c.z);v.camera.updateMatrixWorld();v.stadium.grass.update(v.camera.position,c,0);g.positionLabels();v.draw();});
 await p.screenshot({path:'test-results/camera-turf/tire-debris.png'});
 const arrow=await p.evaluate(async()=>{const g=window.__game,T=await import('/node_modules/.vite/deps/three.js'),r=g.view.ballDirection.root;r.position.set(0,0,0);r.quaternion.identity();r.updateMatrixWorld(true);const size=new T.Box3().setFromObject(r).getSize(new T.Vector3());return{size:size.toArray(),shaft:r.getObjectByName('ball-arrow-shaft').geometry.type,tip:r.getObjectByName('ball-arrow-tip').geometry.type};});
 check('The smaller ball arrow has a cylindrical shaft and cone tip',arrow.size[2]<.16&&arrow.size[0]<.07&&arrow.shaft==='CylinderGeometry'&&arrow.tip==='ConeGeometry',arrow);
 const hint=await p.evaluate(()=>{const g=window.__game;g.hud.camera(true);g.controls.lastDevice='gamepad';g.controls.pad={id:'DualSense Wireless Controller',mapping:'standard'};g.hud.bindings(g.controls);const key=document.querySelector('#ball-cam-key');const on=!document.querySelector('.ball-cam-corner').hidden,ps=key.textContent==='△';g.hud.camera(false);const off=document.querySelector('.ball-cam-corner').hidden;g.controls.lastDevice='keyboard';g.hud.bindings(g.controls);g.hud.camera(true);return{on,off,ps,keyboard:key.textContent};});
 check('The red corner cue appears only in ball cam and follows the active binding',hint.on&&hint.off&&hint.ps&&hint.keyboard==='C',hint);
 await p.locator('.ball-cam-corner').screenshot({path:'test-results/camera-turf/ball-cam-corner.png'});
 check('No browser or shader errors',errors.length===0,errors);await writeFile('test-results/camera-turf/checks.json',JSON.stringify({results,errors},null,2));
}finally{await browser.close()}
