import {chromium} from 'playwright';import assert from 'node:assert/strict';import {writeFile,mkdir} from 'node:fs/promises';
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[],results=[];page.on('pageerror',e=>errors.push(e.message));
const check=(name,pass,detail)=>{results.push({name,pass,detail});console.log(`${pass?'PASS':'FAIL'} ${name}${pass?'':' '+JSON.stringify(detail)}`);};
try{
await mkdir('test-results/feel',{recursive:true});await page.goto('http://127.0.0.1:5179');await page.waitForFunction(()=>window.__game?.view&&!document.querySelector('#loading'));
const hits=await page.evaluate(()=>{const g=window.__game,results=[];for(const speed of [2,4,7,14,23]){g.scenario('drive');g.physics.resetCar(g.physics.player,0,3);g.advance(.3);g.physics.ball.setTranslation({x:0,y:.92,z:1.3},true);g.physics.player.body.setLinvel({x:0,y:0,z:-speed},true);const before=g.hits;for(let i=0;i<120;i++){g.advance(1/120,{throttle:1,boost:speed>20});if(g.hits>before){results.push({speed,impactSpeed:g.physics.player.speed,ball:{...g.physics.ball.linvel()}});break;}}}return results;});
// Measured in the same deterministic approach before this tuning pass.
const before=[{speed:2,y:2.332756996,z:-4.726567268},{speed:4,y:3.158452511,z:-6.432328224},{speed:7,y:4.457740784,z:-9.473050117},{speed:14,y:7.727140903,z:-16.812877655},{speed:23,y:11.493459702,z:-27.388019562}];
for(let i=0;i<hits.length;i++){const ratio=hits[i].ball.z/before[i].z,up=hits[i].ball.y/before[i].y;check(`Impact power at approach speed ${hits[i].speed}`,i<2?ratio>.885&&ratio<.92:i===2?ratio>.92&&ratio<.98:Math.abs(ratio-1)<.005,{...hits[i],ratio,up});check(`Head-on lift trimmed gently at ${hits[i].speed}`,up>.84&&up<.98,{up});}
const crowd=await page.evaluate(async()=>{const {Matrix4,Vector3}=await import('/node_modules/.vite/deps/three.js');const g=window.__game,c=g.view.scene.getObjectByName('stadium-crowd'),m=new Matrix4(),pos=new Vector3(),scale=new Vector3();let intruders=0;for(let i=0;i<c.count;i++){c.getMatrixAt(i,m);pos.setFromMatrixPosition(m);scale.setFromMatrixScale(m);if(Math.abs(pos.x)-scale.x*.14<8.93&&Math.abs(pos.z)-scale.z*.14<60.1&&Math.abs(pos.z)+scale.z*.14>51&&pos.y-scale.y*.14<6.7)intruders++;}let seats=0;g.view.scene.getObjectByName('end-stands').traverse(o=>{if(!o.geometry)return;const a=o.geometry.attributes.position;for(let i=0;i<a.count;i++)if(Math.abs(a.getX(i))<9.2&&Math.abs(a.getZ(i))<60.5&&a.getY(i)<6.9)seats++;});return{intruders,seats,count:c.count};});
check('Spectators and seating clear both goal volumes',crowd.intruders===0&&crowd.seats===0&&crowd.count===10500,crowd);
const rides=[];
for(const end of [-1,1])for(const direction of ['left','right','back']){
const ride=await page.evaluate(({end,direction})=>{const g=window.__game;g.scenario('drive');g.physics.ball.setTranslation({x:20,y:1,z:0},true);const yaw=direction==='left'?Math.PI/2:direction==='right'?-Math.PI/2:end>0?Math.PI:0;g.physics.resetCar(g.physics.player,0,end*55.7,yaw);let max=0,up=false,minSpeed=100;const trace=[];for(let i=0;i<180;i++){g.advance(1/120,{throttle:1,boost:true});const c=g.physics.player,p=c.body.translation();max=Math.max(max,p.y);if(p.y>2.2&&c.grounded)up=true;if(i>35&&i<90)minSpeed=Math.min(minSpeed,c.speed);if(i%30===0)trace.push({p:{...p},wheels:c.wheels,speed:c.speed});}return{end,direction,max,up,minSpeed,trace};},{end,direction});rides.push(ride);check(`Wide goal ramp drives onto ${end} ${direction} wall`,ride.max>3&&ride.up&&ride.minSpeed>2,ride);
}
const framing=[];
for(const ball of [[0,19,10],[0,19,28],[0,19,29],[15,16,27],[0,5,32],[0,1,0]]){
const view=await page.evaluate(ball=>{const g=window.__game;g.scenario('drive');g.advance(.3);g.hud.camera(true);g.view.shake=0;g.view.ballCam=true;g.view.cameraReady=false;g.physics.ball.setTranslation({x:ball[0],y:ball[1],z:ball[2]},true);for(let i=0;i<150;i++)g.view.update(1/60,'playing');g.view.draw();return{ball,ballScreen:g.view.ball.position.clone().project(g.view.camera).toArray(),carScreen:g.view.player.root.position.clone().project(g.view.camera).toArray(),camera:g.view.camera.position.toArray()};},ball);framing.push(view);check(`Ball cam frames car and ball at ${ball.join(',')}`,view.ballScreen[2]<1&&Math.abs(view.ballScreen[0])<.88&&Math.abs(view.ballScreen[1])<.84&&Math.abs(view.carScreen[0])<.92&&Math.abs(view.carScreen[1])<.83,view);
if(ball[2]===29)await page.screenshot({path:'test-results/feel/ball-overhead.png'});
}
const sweep=await page.evaluate(()=>{const g=window.__game;g.scenario('drive');g.physics.resetCar(g.physics.player,0,0);g.view.ballCam=true;g.view.cameraReady=false;g.physics.ball.setTranslation({x:0,y:2,z:-12},true);g.view.update(0,'playing');const trace=[];let last=g.view.camera.quaternion.clone(),maxAngle=0,maxStep=0,offscreen=0;for(let i=0;i<600;i++){const t=i/60;const ball={x:10*Math.sin(t*.6),y:2+16*Math.sin(Math.PI*t/10)**2,z:-12*Math.cos(t*.6)};g.physics.ball.setTranslation(ball,true);const old=g.view.camera.position.clone();g.view.update(1/60,'playing');maxAngle=Math.max(maxAngle,last.angleTo(g.view.camera.quaternion));maxStep=Math.max(maxStep,old.distanceTo(g.view.camera.position));last.copy(g.view.camera.quaternion);const p=g.view.ball.position.clone().project(g.view.camera);if(i>30&&(Math.abs(p.x)>.95||Math.abs(p.y)>.95||p.z>1))offscreen++;if(i%60===0)trace.push({t,p:p.toArray(),camera:g.view.camera.position.toArray()});}return{maxAngle,maxStep,offscreen,trace};});
check('Moving high ball remains framed through a full orbit',sweep.offscreen===0,sweep);check('Ball-cam orbit has bounded continuous motion',sweep.maxAngle<.085&&sweep.maxStep<.65,sweep);
const overhead=await page.evaluate(()=>{const g=window.__game;g.scenario('drive');g.physics.resetCar(g.physics.player,0,0);g.view.ballCam=true;g.view.cameraReady=false;g.physics.ball.setTranslation({x:0,y:19,z:-8},true);g.view.update(0,'playing');let maxAngle=0,offscreen=0,last=g.view.camera.quaternion.clone();for(let i=0;i<240;i++){g.physics.ball.setTranslation({x:0,y:19,z:-8+i/15},true);g.view.update(1/60,'playing');maxAngle=Math.max(maxAngle,last.angleTo(g.view.camera.quaternion));last.copy(g.view.camera.quaternion);const p=g.view.ball.position.clone().project(g.view.camera);if(Math.abs(p.y)>.95||Math.abs(p.x)>.95||p.z>1)offscreen++;}return{maxAngle,offscreen};});check('Direct overhead crossing does not snap or lose the ball',overhead.maxAngle<.11&&overhead.offscreen===0,overhead);
for(const end of [-1,1]){
await page.evaluate(end=>{const g=window.__game;g.scenario('drive');g.physics.resetCar(g.physics.player,0,end*55.3,end>0?Math.PI:0);g.view.camera.position.set(0,3.5,end*49);g.view.look.set(6,2.5,end*58);g.view.camera.lookAt(g.view.look);g.view.camera.updateMatrixWorld();g.view.draw();},end);await page.screenshot({path:`test-results/feel/goal-${end}.png`});}
const refresh=await page.evaluate(async()=>{const {FollowCamera}=await import('/src/follow-camera.ts');const {PerspectiveCamera,Vector3,Quaternion}=await import('/node_modules/.vite/deps/three.js');const states=[];for(const fps of [30,60,144]){const rig=new FollowCamera(),camera=new PerspectiveCamera(69,1.6,.15,550),pos=new Vector3(0,.335,0),q=new Quaternion(),ball=new Vector3(0,2,-12),clear=(a,b)=>a.distanceTo(b);rig.update(camera,pos,q,ball,0,true,false,0,true,clear);for(let i=1;i<=fps*8;i++){const t=i/fps;ball.set(12*Math.sin(t*.3),2+10*Math.sin(Math.PI*t/8)**2,-12*Math.cos(t*.3));rig.update(camera,pos,q,ball,0,true,false,1/fps,false,clear);}states.push({fps,position:camera.position.toArray(),rotation:camera.quaternion.toArray()});}const a=states[0],b=states[2];return{states,distance:new Vector3(...a.position).distanceTo(new Vector3(...b.position)),angle:new Quaternion(...a.rotation).angleTo(new Quaternion(...b.rotation))};});
check('Camera response remains consistent at 30, 60 and 144 Hz',refresh.distance<.3&&refresh.angle<.035,refresh);
check('No browser errors',errors.length===0,errors);await writeFile('test-results/feel/report.json',JSON.stringify({results,hits,rides,framing,sweep,overhead,refresh,errors},null,2));assert.ok(results.every(r=>r.pass),`${results.filter(r=>!r.pass).length} feel checks failed`);
}finally{await browser.close();}
