import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';

const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', args: ['--no-sandbox', '--disable-dev-shm-usage'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
page.on('console', e => { if (e.type() === 'error') errors.push(e.text()); });
const results = [];
const check = (name, pass, detail) => { assert.ok(pass, `${name}: ${JSON.stringify(detail)}`); results.push({ name, detail }); console.log(`PASS ${name}`); };
const run = (code, arg) => page.evaluate(code, arg);
try {
  await page.goto(process.env.GAME_URL || 'http://127.0.0.1:5179');
  await page.waitForFunction(() => window.__game?.view && !document.querySelector('#loading'));
  await mkdir('test-results', { recursive: true });
  await page.screenshot({ path: 'test-results/arena.png' });
  check('WebGL scene and detailed assets load', await run(() => window.__game.view.player.root.children.some(x => x.isMesh && x.geometry.attributes.position.count > 1000)), {});
  check('New match starts with ball cam on', await run(() => window.__game.view.ballCam && document.querySelector('#camera-status').textContent === 'ON'), {});
  await page.keyboard.down('w');
  await page.waitForFunction(() => window.__game.phase === 'playing');
  await page.waitForFunction(() => window.__game.physics.player.body.translation().z < 25);
  await page.keyboard.up('w');
  let s = await run(() => window.__game.snapshot());
  check('Real keyboard starts match and drives', s.car.z < 25 && s.remaining < 300, s.car);
  await page.keyboard.press('Escape');
  const frozen = await run(() => window.__game.snapshot());
  await page.waitForTimeout(450);
  check('Pause freezes simulation and timer', await run(t => window.__game.remaining === t && window.__game.paused, frozen.remaining), frozen.remaining);
  check('Pause quiets the engine', await run(() => (window.__game.view.audio.engineGain?.gain.value ?? 0) < .01), {});
  await page.getByRole('button', { name: 'BACK TO THE FIELD' }).click();
  check('Resume button works', await run(() => !window.__game.paused), {});
  await page.keyboard.press('b');
  check('B enables unlimited boost', await run(() => window.__game.physics.unlimited), {});
  await page.keyboard.press('b');
  await page.keyboard.press('c');
  check('C toggles ball camera off', await run(() => !window.__game.view.ballCam && document.querySelector('#camera-status').textContent === 'OFF'), {});
  await page.keyboard.press('c');
  check('C toggles ball camera back on', await run(() => window.__game.view.ballCam), {});
  await page.keyboard.press('h');
  check('Controls guide opens', await page.locator('#help-panel').isVisible(), {});
  await page.getByRole('button', { name: "LET'S PLAY" }).click();

  s = await run(() => { const g = window.__game; g.scenario('collision'); return g.advance(1, { throttle: 1 }); });
  check('Car transfers momentum to ball', s.hits > 0 && s.ball.z < -2 && s.ballVelocity.z < -7, { ball: s.ball, velocity: s.ballVelocity });
  s = await run(() => { const g = window.__game; g.scenario('drive'); g.advance(.3); return g.advance(.75, { throttle: 1, steer: 1 }); });
  check('Steering turns while accelerating', Math.abs(s.rotation.y) > .2 && s.car.x < -1, { rotation: s.rotation, car: s.car });
  s = await run(() => { const g = window.__game; g.scenario('drive'); g.advance(.3); return g.advance(.23, { jump: true, jumpHeld: true }); });
  check('Ground jump and hold gain height', s.car.y > 1 && s.jumps === 1 && !s.grounded, { y: s.car.y, jumps: s.jumps });
  s = await run(() => { const g = window.__game; return g.advance(.23, { jump: true }); });
  check('Second jump adds upward velocity', s.car.y > 2 && s.jumps === 2, { y: s.car.y, jumps: s.jumps });
  s = await run(() => { const g = window.__game; g.scenario('air'); return g.advance(.2, { jump: true, throttle: 1 }); });
  check('Directional dodge rotates and accelerates', s.velocity.z < -4 && Math.abs(s.rotation.x) > .5, { velocity: s.velocity, rotation: s.rotation });
  s = await run(() => { const g = window.__game; g.scenario('air'); return g.advance(.3, { roll: 1 }); });
  check('Air roll responds', Math.abs(s.rotation.z) > .15, s.rotation);
  s = await run(() => { const g = window.__game; g.scenario('drive'); g.physics.resetCar(g.physics.player, 8, 29); return g.advance(.8, { throttle: 1, boost: true }); });
  check('Boost drains and increases speed', s.boost < 85 && Math.hypot(s.velocity.x, s.velocity.z) > 13, { boost: s.boost, velocity: s.velocity });
  s = await run(() => { const g = window.__game; g.scenario('drive'); g.physics.resetCar(g.physics.player, 8, 29); g.physics.unlimited = true; return g.advance(.8, { throttle: 1, boost: true }); });
  check('Unlimited boost stays full under use', s.boost === 100, s.boost);
  await run(() => { window.__game.physics.unlimited = false; });
  s = await run(() => { const g = window.__game; g.scenario('pad'); return g.advance(.7, { throttle: 1 }); });
  check('Small boost pads add 12', s.boost === 27, s.boost);
  s = await run(() => { const g = window.__game; g.scenario('big-pad'); return g.advance(.7, { throttle: 1 }); });
  check('Large boost pads refill tank', s.boost === 100, s.boost);
  const cooldown = await run(() => window.__game.physics.pads.find(p => p.x === -31 && p.z === 0).cooldown);
  check('Collected pad enters cooldown', cooldown > 9, cooldown);
  await run(() => window.__game.advance(10.1));
  check('Pad respawns after cooldown', await run(() => window.__game.physics.pads.find(p => p.x === -31 && p.z === 0).cooldown === 0), {});
  s = await run(() => { const g = window.__game; g.scenario('goal-blue'); return g.advance(.6); });
  check('Blue goal scores once', s.blue === 1 && s.phase === 'goal', { blue: s.blue, phase: s.phase });
  await run(() => window.__game.view.draw());
  await page.screenshot({ path: 'test-results/goal.png' });
  s = await run(() => window.__game.advance(1));
  check('Goal cannot score repeatedly', s.blue === 1, s.blue);
  s = await run(() => window.__game.advance(6.8));
  check('Goal celebration resets to playable kickoff', s.phase === 'playing' && Math.abs(s.ball.z) < .01 && s.car.z === 29, { phase: s.phase, ball: s.ball, car: s.car });
  s = await run(() => { const g = window.__game; g.scenario('goal-orange'); return g.advance(.6); });
  check('Orange goal scores', s.orange === 1 && s.phase === 'goal', { orange: s.orange, phase: s.phase });
  const partial = await run(() => { const g = window.__game; g.scenario('drive'); g.physics.ball.setTranslation({ x: 0, y: 2, z: -52.1 }, true); return g.physics.goal(); });
  check('Ball must cross fully over goal line', partial === null, partial);
  const post = await run(() => { const g = window.__game; g.physics.ball.setTranslation({ x: 12, y: 2, z: -50 }, true); return g.physics.goal(); });
  check('Outside goal mouth is not a score', post === null, post);
  s = await run(() => { const g = window.__game; g.scenario('wall'); return g.advance(.5); });
  check('Ball rebounds off arena wall', s.ballVelocity.x < -10 && s.ball.x < 40, { ball: s.ball, velocity: s.ballVelocity });
  s = await run(() => { const g = window.__game; g.scenario('wall-drive'); return g.advance(1.8, { throttle: 1, boost: true }); });
  check('Car climbs curved wall transition', s.car.y > 5 && Math.abs(s.car.x) < 41, s.car);
  s = await run(() => { const g = window.__game; g.scenario('flip-reset'); return g.advance(.2); });
  check('Four wheel ball contact restores flip', s.jumps === 0, { jumps: s.jumps, y: s.car.y });
  const cancelled = await run(() => { const g = window.__game; g.scenario('air'); g.advance(.25, { jump: true, throttle: 1 }); g.advance(.03, { pitch: 1 }); return g.physics.player.flipTime; });
  check('Opposing pitch cancels a forward flip', cancelled === 0, cancelled);
  s = await run(() => { const g = window.__game; g.scenario('air'); g.physics.player.airTime = 2; return g.advance(.05, { jump: true }); });
  check('Expired airborne dodge cannot be reused', s.jumps === 1, s.jumps);
  const ceiling = await run(() => { const g = window.__game; g.scenario('drive'); g.physics.ball.setTranslation({ x: 0, y: 18, z: 10 }, true); g.physics.ball.setLinvel({ x: 0, y: 35, z: 0 }, true); g.advance(.25); return g.snapshot(); });
  check('High ball rebounds off ceiling bound', ceiling.ball.y < 20.48 && ceiling.ballVelocity.y < 0, { ball: ceiling.ball, velocity: ceiling.ballVelocity });
  const camera = await run(() => { const g = window.__game; g.scenario('wall-drive'); g.view.ballCam = true; for (let i = 0; i < 105; i++) g.advance(1 / 60, { throttle: 1, boost: true }); const p = g.view.player.root.position.clone().project(g.view.camera); return { x: p.x, y: p.y, z: p.z, camera: g.view.camera.position.toArray() }; });
  check('Wall ball-cam keeps car visible', Math.abs(camera.x) < .95 && Math.abs(camera.y) < .95 && camera.z < 1, camera);
  const demo = await run(() => { const g = window.__game; g.scenario('drive'); g.physics.botEnabled = true; g.physics.ball.setTranslation({ x: 15, y: 1, z: 0 }, true); g.physics.resetCar(g.physics.player, 0, 4); g.physics.resetCar(g.physics.bot, 0, 0); g.physics.player.body.setLinvel({ x: 0, y: 0, z: -23 }, true); g.advance(.3, { throttle: 1, boost: true }); return g.physics.bot.demolished; });
  check('Supersonic tackle demolishes opponent', demo > 0, demo);
  await run(() => window.__game.advance(2.8));
  check('Demolished opponent respawns', await run(() => window.__game.physics.bot.demolished === 0 && window.__game.physics.bot.body.translation().y > 0), {});
  s = await run(() => { const g = window.__game; g.scenario('rollover'); return g.advance(2, { throttle: 1 }); });
  check('Stationary overturned car recovers', Math.abs(s.rotation.w) > .9, s.rotation);
  s = await run(() => { const g = window.__game; g.scenario('drive'); g.physics.botEnabled = true; g.blue = 2; g.orange = 1; g.remaining = .15; return g.advance(.4); });
  check('Match ends with winner', s.phase === 'ended', s.phase);
  s = await run(() => { const g = window.__game; g.scenario('drive'); g.physics.botEnabled = true; g.blue = g.orange = 0; g.remaining = .1; return g.advance(.5); });
  check('Tied match enters overtime', s.overtime && s.phase === 'countdown', { overtime: s.overtime, phase: s.phase });
  s = await run(() => { const g = window.__game; g.advance(3.1); g.physics.ball.setTranslation({ x: 0, y: 1.5, z: -45 }, true); g.physics.ball.setLinvel({ x: 0, y: 0, z: -22 }, true); return g.advance(5.3); });
  check('Next overtime goal ends match', s.phase === 'ended' && s.blue === 1, { phase: s.phase, blue: s.blue });
  check('Match end clears goal effects', await run(() => !window.__game.view.effects.explosion.root.visible), {});
  await run(() => { const g = window.__game; g.restart(); g.physics.botEnabled = true; g.testing = false; g.view.ballCam = false; g.hud.camera(false); });
  await page.setViewportSize({ width: 900, height: 600 });
  await page.screenshot({ path: 'test-results/compact.png' });
  check('Viewport resize follows canvas', await run(() => document.querySelector('canvas').clientWidth === 900 && window.__game.view.camera.aspect === 1.5), {});
  check('No browser errors', errors.length === 0, errors);
  await writeFile('test-results/results.json', JSON.stringify({ tests: results.length, results, errors }, null, 2));
} finally { await browser.close(); }
