import {chromium} from 'playwright';import {mkdir,writeFile} from 'node:fs/promises';
await mkdir('test-results/impact/visuals',{recursive:true});const b=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--no-sandbox']});try{
const p=await b.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});const errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await p.goto('http://127.0.0.1:5179');await p.waitForFunction(()=>window.__game?.view&&!document.querySelector('#loading'));
await p.evaluate(()=>{const g=window.__game;g.scenario('drive');g.physics.botEnabled=true;g.physics.resetCar(g.physics.player,-3,9);g.physics.resetCar(g.physics.bot,0,0);g.physics.ball.setTranslation({x:12,y:1,z:0},true);g.physics.demolish(g.physics.bot);g.view.shake=0;g.view.cameraReady=true;g.view.camera.position.set(4,3.2,10);g.view.camera.lookAt(0,1.4,0);g.view.camera.updateMatrixWorld();});
let previous=0;for(const t of [.04,.16,.35,.7,1.4,2.4,3.2]){await p.evaluate(dt=>{const g=window.__game;for(let n=0;n<Math.ceil(dt*120);n++)g.view.effects.update(dt/Math.ceil(dt*120));g.view.update(0,'playing');g.view.draw();},t-previous);previous=t;await p.screenshot({path:`test-results/impact/visuals/demo-${t}.png`});}
await p.evaluate(()=>{const g=window.__game;g.scenario('drive');g.view.effects.demolitions.reset();g.physics.botEnabled=true;g.physics.resetCar(g.physics.player,3,-44);g.physics.resetCar(g.physics.bot,-4,-38);g.physics.ball.setTranslation({x:0,y:2,z:-53},true);g.view.ballCam=true;g.view.cameraReady=false;g.view.update(0,'playing');g.score('blue');});
previous=0;const trace=[];for(const t of [.2,.5,1,1.6,2.5,3.8,4.7]){trace.push(await p.evaluate(dt=>{const g=window.__game;for(let i=0;i<Math.ceil(dt*120);i++){g.tick({throttle:0,steer:0,pitch:.25,roll:1,boost:false,jump:false,jumpHeld:false,drift:false});g.view.update(1/120,g.phase,g.celebration);}g.view.draw();return{phase:g.phase,car:g.snapshot().car,camera:g.view.camera.position.toArray(),projection:g.view.player.root.position.clone().project(g.view.camera).toArray()};},t-previous));previous=t;await p.screenshot({path:`test-results/impact/visuals/goal-${t}.png`});}
await p.evaluate(()=>{const g=window.__game;g.scenario('drive');g.physics.resetCar(g.physics.player,0,51);g.view.update(0,'playing');g.view.cameraReady=true;g.view.camera.position.set(-3,3.2,49);g.view.camera.lookAt(1,2,58);g.view.camera.updateMatrixWorld();g.view.draw();});
await p.screenshot({path:'test-results/impact/visuals/transparent-goal.png'});
await p.evaluate(async()=>{const T=await import('/node_modules/.vite/deps/three.js'),g=window.__game;g.scenario('drive');g.view.ballCam=false;g.physics.ball.setTranslation({x:0,y:1,z:-12},true);g.view.effects.demolitions.trigger(new T.Vector3(0,.35,0),new T.Vector3(),new T.Quaternion(),0xff942e);});
previous=0;for(const [z,t] of [[6,.12],[2,.35],[-2,.65],[-5,1.1]]){await p.evaluate(({z,dt})=>{const g=window.__game;g.physics.resetCar(g.physics.player,0,z);g.view.effects.update(dt);g.view.cameraReady=false;g.view.update(0,'playing');g.view.draw();},{z,dt:t-previous});previous=t;await p.screenshot({path:`test-results/impact/visuals/drive-through-${t}.png`});}
console.log(JSON.stringify({trace,errors}));await writeFile('test-results/impact/visuals/report.json',JSON.stringify({trace,errors},null,2));
}finally{await b.close();}
