import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),results=[],errors=[];
const check=(name,pass,detail)=>{assert.ok(pass,`${name}: ${JSON.stringify(detail)}`);results.push({name,detail});console.log(`PASS ${name}`)};
try{const p=await browser.newPage({viewport:{width:1440,height:900}});p.on('pageerror',e=>errors.push(e.message));p.on('console',e=>{if(e.type()==='error')errors.push(e.text())});await p.goto('http://127.0.0.1:5179');await p.waitForFunction(()=>window.__game?.view&&!document.querySelector('#loading'));
 const steering=await p.evaluate(async()=>{const g=window.__game,{emptyInput}=await import('/src/config.ts'),T=await import('/node_modules/.vite/deps/three.js'),rows=[];
  const settle=()=>{g.scenario('drive');g.physics.ball.setEnabled(false);g.physics.resetCar(g.physics.player,0,0);for(let i=0;i<120;i++)g.physics.step(emptyInput(),emptyInput());};
  for(const steer of [-1,1])for(const drift of [false,true]){settle();const c=g.physics.player,position=new T.Vector3().copy(c.body.translation()),rotation=new T.Quaternion().copy(c.body.rotation());let maxTurn=0;for(let i=0;i<600;i++){g.physics.step({...emptyInput(),steer,drift},emptyInput());maxTurn=Math.max(maxTurn,Math.abs(c.body.angvel().y));}rows.push({steer,drift,distance:position.distanceTo(new T.Vector3().copy(c.body.translation())),angle:rotation.angleTo(new T.Quaternion().copy(c.body.rotation())),maxTurn});}
  const speeds=[];for(const speed of [-10,-3.5,-1,-.25,0,.25,1,3.5,10]){settle();const c=g.physics.player;c.body.setLinvel({x:0,y:0,z:-speed},true);g.physics.step({...emptyInput(),steer:1},emptyInput());speeds.push({speed,turn:c.body.angvel().y});}
  const moving=[];for(const throttle of [-1,1]){settle();const c=g.physics.player;for(let i=0;i<120;i++)g.physics.step({...emptyInput(),throttle,steer:.7},emptyInput());const forward=new T.Vector3(0,0,-1).applyQuaternion(c.body.rotation());moving.push({throttle,yaw:Math.atan2(-forward.x,-forward.z),distance:new T.Vector3().copy(c.body.translation()).length()});}
  settle();const c=g.physics.player;c.body.setLinvel({x:0,y:0,z:-5},true);for(let i=0;i<300;i++)g.physics.step({...emptyInput(),steer:1},emptyInput());const coasting={speed:Math.hypot(c.body.linvel().x,c.body.linvel().z),turn:Math.abs(c.body.angvel().y)};
  return{rows,speeds,moving,coasting};});
 check('Steering alone cannot rotate a stationary car, including powerslide',steering.rows.every(r=>r.angle<.01&&r.distance<.01&&r.maxTurn<.01),steering.rows);
 check('Slow rolling steering scales down smoothly and reverses with travel',[-1,1].every(sign=>{const rows=steering.speeds.filter(r=>r.speed*sign>0).sort((a,b)=>Math.abs(a.speed)-Math.abs(b.speed));return rows.every((r,i)=>r.turn*sign>0&&(i===0||Math.abs(r.turn)>=Math.abs(rows[i-1].turn)-.03))&&Math.abs(rows[0].turn)<.25&&Math.abs(rows[0].turn)<Math.abs(rows.at(-1).turn)*.15;}),steering.speeds);
 check('Forward and reverse driving still turn in the correct directions',steering.moving.every(r=>r.yaw*r.throttle>.5&&r.distance>2),steering.moving);
 check('Steering settles as the coasting car comes to rest',steering.coasting.speed<.05&&steering.coasting.turn<.02,steering.coasting);
 const boost=await p.evaluate(()=>{const g=window.__game,v=g.view;g.scenario('drive');g.physics.player.boosting=true;v.setBoostStyle('inferno');for(let i=0;i<30;i++)v.update(1/60,'playing');const inferno={core:v.boosts[0].root.visible,smoke:v.infernos[0].root.count};v.setBoostStyle('classic');for(let i=0;i<10;i++)v.update(1/60,'playing');const classic={core:v.boosts[0].root.visible,smoke:v.infernos[0].root.count};v.setBoostStyle('inferno');v.update(0,'playing');return{inferno,classic,pausedCore:v.boosts[0].root.visible};});
 check('Inferno uses its smoke plume with no extra nozzle flame',!boost.inferno.core&&boost.inferno.smoke>0&&!boost.pausedCore,boost);
 check('Classic retains its original flame and clears Inferno smoke',boost.classic.core&&boost.classic.smoke===0,boost);
 check('No browser or shader errors',errors.length===0,errors);await mkdir('test-results/steering-boost',{recursive:true});await writeFile('test-results/steering-boost/checks.json',JSON.stringify({results,errors},null,2));
}finally{await browser.close()}
